INSERT into category (description) values ('American');
INSERT into category (description) values ('Italian');
INSERT into category (description) values ('Mexican');
INSERT into category (description) values ('Fast Food');
INSERT  INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT  INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT  INTO unit_of_measure (description) VALUES ('Cup');
INSERT  INTO unit_of_measure (description) VALUES ('Pinch');
INSERT  INTO unit_of_measure (description) VALUES ('Ounce');
INSERT  INTO unit_of_measure (description) VALUES ('Each');
INSERT  INTO unit_of_measure (description) VALUES ('Pint');
INSERT  INTO unit_of_measure (description) VALUES ('Dash');
INSERT  INTO unit_of_measure (description) VALUES ('Piece');
INSERT  INTO unit_of_measure (description) VALUES ('Pound');
INSERT  INTO unit_of_measure (description) VALUES ('Unit');
INSERT  INTO unit_of_measure (description) VALUES ('Can');
INSERT  INTO unit_of_measure (description) VALUES ('Slice');
INSERT  INTO unit_of_measure (description) VALUES ('Package');
INSERT  INTO unit_of_measure (description) VALUES ('Bunch');

